# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'meej.unmapped' to control all apps that aren't bound to any slider (except master, system, mic and device-targeting sessions)
# windows only - you can use 'meej.current' to control the currently focused app
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
slider_mapping:
  0: master
  1:
   - zen.exe
   - obs64.exe

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# you can disable the tray icon if you system doesn't support it, or you just don't need it
disable_tray: false

# fast reconnect allows meej to detect disconnection faster by constantly scanning for the device
# with this option disabled, it relies on OS disconnect notification which might be quite delayed
# especially on Windows
# don't use it on Linux as it doesn't have this problem
# actually fast reconnect works worse on it
fast_reconnect: true

# these parameters are applied to mixy
# they allow to make mixy more responsive
# but extreme values will drain the battery much faster
# try to keep intervals high and timeout low
# both are expressed in milliseconds
mixy_params:
  change_threshold: 9   # minimum change in slider raw reading to trigger an update
  slow_interval: 400    # time between slider readings in idle mode
  fast_interval: 80     # time between slider readings when in fast mode
  fast_timeout: 300     # time to stay in fast mode after the last change
