name: Build

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        mode: [ release, dev ]
        go: [ "1.24" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Build meej for Linux
        if: runner.os == 'Linux'
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          VERSION_TAG=${{ github.ref_name }}
          BUILD_TYPE=${{ matrix.mode }}
          if [ "$BUILD_TYPE" = "release" ]; then
            LDFLAGS="-s -w"
          else
            LDFLAGS=""
          fi
          go build -o meej-linux-x86_64-$BUILD_TYPE -ldflags "$LDFLAGS -X main.gitCommit=$GIT_COMMIT -X main.versionTag=$VERSION_TAG -X main.buildType=$BUILD_TYPE" ./pkg/meej/cmd

      - name: Build meej for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $GIT_COMMIT = (git rev-parse --short HEAD)
          $VERSION_TAG = "${{ github.ref_name }}"
          $BUILD_TYPE = "${{ matrix.mode }}"
          if ($BUILD_TYPE -eq "release") {
            $LDFLAGS = "-s -w"
          } else {
            $LDFLAGS = ""
          }
          go build -o meej-windows-x86_64-$BUILD_TYPE.exe -ldflags "$LDFLAGS -X main.gitCommit=$GIT_COMMIT -X main.versionTag=$VERSION_TAG -X main.buildType=$BUILD_TYPE" ./pkg/meej/cmd

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: meej-*
          tag: ${{ github.ref }}
          file_glob: true
